public enum MajorItem
{
    None = 0,
    RocketLauncher = 1, //Energy Weapon, Explosive
    Dash = 2,
    FireBolt = 3, //Shot Mod
    ElectroCharge = 4, //Shot Mod
    LightningGun = 5, //Energy Weapon
    Flamethrower = 6, //Energy Weapon
    DoubleJump = 7,  //Jump
    Slide = 8,
    JetPack = 9, //Flight
    HeatShell = 10, //Shell, Env Survival
    GlowBot = 11, //Orb, Light
    PowerJump = 12, //Jump
    ExplosiveBolt = 13, //Shot Mod, Explosive
    BrightShell = 14, //Shell, Light
    PhaseShot = 15, //Shot Mod
    Infinijump = 16, //Flight
    ViridianShell = 17, //Shell, Flight
    Arachnomorph = 18,
    RailGun = 19, //Energy Weapon, Phasing
    CognitiveStabilizer = 20, //Helm, Env Survival
    HoverBoots = 21, //Jump
    BuzzsawShell = 22, //Velocity Damage
    Phaserang = 23, //Energy Weapon, Phasing
    NecroluminantSpray = 24, //Energy Weapon, Light
    UpDog = 25, // Energy Weapon, Jump
    DiveShell = 26, //Env Survive Water
    Kaboomerang = 27, //Orb, Phasing, Explosive
    HellfireCannon = 28, //Energy Weapon, Fire
    PhaseShell = 29, //Phasing
    //BuzzsawGun = 29.5, //Found Below
    PulseMGL = 30,

    //Non Traversal Items Start at 100

    //Orbs (start at 100)
    ShootOrb = 100,
    ShieldOrb = 101,
    TriOrb = 102,
    AutoTurret = 103,
    RoyalOrb = 104,
    BuzzOrb = 105,
    HunterKiller = 106,
    HealthOrb = 107,
    Explorb = 108,
    Mothorb = 109, //Bum Type
    TheThief = 110, //Bum Type
    EnergyVorb = 111, //Bum Type
    ScrapVorb = 112, //Bum Type
    HealthVorb = 113, //Bum Type
    LilTyr = 114, //Bum Type
    LilZurvan = 115, //Bum Type
    LilPhaestus = 116, //Bum Type
    LilWadjet = 117, //Bum Type
    LilBuluc = 118, //Bum Type
    LilOrphy = 119, //Bum Type
    PrismaticOrb = 120,
    Lasorb = 121,
    TwinOrb = 122,
    ToxinOrb = 123,

    //Guns (start at 200)
    TripleShot = 200, //Shot Mod
    PenetrativeShot = 201, //Shot Mod
    BuzzsawGun = 202, //Energy Weapon, ALSO TRAVERSAL
    HomingBolt = 203, //Shot Mod
    FragmentShot = 204, //Shot Mod
    LaserBeam = 205, //Energy Weapon
    AuraBolt = 206, //Shot Mod
    BigBolt = 207, //Shot Mod
    ScatterGun = 208, //Energy Weapon
    MachineGun = 209, //Energy Weapon
    ToxinBolt = 210, //Shot Mod
    ToxinSpray = 211, //Energy Weapon
    WebBolt = 212, //Shot Mod
    ArtificeBeam = 213, //Energy Weapon
    BounceBolt = 214, //Shot Mod
    LaoziBolt = 215, //Shot Mod
    SwellBolt = 216, //Shot Mod
    ScrapBooster = 217, //Shot Mod
    HealthBooster = 218, //Shot Mod
    HiveBolt = 219, //Shot Mod
    RotaryBolt = 220, //Shot Mod

    //Other (start at 300)
    WreckingShell = 300,
    SpeedShell = 301,
    CaveMap = 302,
    FactoryMap = 303,
    BuriedCityMap = 304,
    MegaHealth = 305,
    MegaEnergy = 306,
    MegaDamage = 307,
    MegaSpeed = 308,
    MegaAttack = 309,
    AttractorHelm = 310,
    RegenerationHelm = 311,
    AspectShell = 312,
    BossMap = 313,
    ArtifactMap = 314,
    MasterMap = 315,
    GlitchMap = 316,
    ArtificeHelm = 317,
    TheRedKey = 318,
    TheGreenKey = 319,
    TheBlueKey = 320,
    TheBlackKey = 321,
    GlitchShell = 322,
    MegaShotSpeed = 323,
    ChromeDome = 324,
    PowerPauldrons = 325,
    HiveHelm = 326,
    ToxinPauldrons = 327,
    DeadlockBoots = 328,
    TyrsHorns = 329,
    Mechapirote = 330,
    ScrapCache = 331,
    HazardShell = 332,
    CrystalShell = 333,
    BurstPauldrons = 334,
    EnergyBoots = 335,
    BoltHelm = 336,
    HiveShell = 337,
    TrollHelm = 338,
    WraithShell = 339,
    EmpireHelm = 340,

    //Activated/Carried Items (start at 400)
    ETHChip = 400,
    RadialBolts = 401,
    DamageBoostAura = 402,
    NanoswarmGenerator = 403,
    ToxinCloud = 404,
    CelestialCharge = 405,
    EnergyAxe = 406,
    WaveBomb = 407,
    AttackBoostAura = 408,
    SpeedBoostAura = 409,
    ModuleTransmogrifier = 410,
    TheGlitchedKey = 411,
    SearchBurst = 412,
    PowerShield = 413,
    PhantasmalOrbs = 414,
    RepairKit = 415,
    CloakingDevice = 416,
    PersonalTeleporter = 417,
    ZurvansPentangle = 418,
    HandOfHephaestus = 419,
    HTSChip = 420,
    OrphielsAltar = 421,
    SedativeCloud = 422,
    SpontaneousGenerator = 423,
}
